name: Automation - Prepare Release

on:
  workflow_dispatch:
    # Determine the version number that will be assigned to the release. During the beta phase, we increment
    # the minor version number and set the patch number to 0.
    inputs:
      candidate-stable:
        required: true
        description: Release candidate version (stable, like 1.0.0-rc4)

      current-stable:
        required: true
        description: Current version (stable, like 1.0.0-rc3)

      candidate-beta:
        required: true
        description: Release candidate version (beta, like 0.70.0)

      current-beta:
        required: true
        description: Current version (beta, like 0.69.1)
jobs:
  # Releasing ocg
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # To keep track of the progress, it might be helpful to create a tracking issue similar to #6067. You are responsible
      # for all of the steps under the "Performed by ocg release manager" heading. Once the issue is created, you can
      # create the individual ones by hovering them and clicking the "Convert to issue" button on the right hand side.
      - name: Create issue for tracking release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CANDIDATE_BETA: ${{ inputs.candidate-beta }}
          CANDIDATE_STABLE: ${{ inputs.candidate-stable }}
          REPO: Chinwendu20/otel_components_generator
        run: ./.github/workflows/scripts/release-create-tracking-issue.sh
      - name: Check build status in repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: Chinwendu20/otel_components_generator
        run: ./.github/workflows/scripts/release-check-build-status.sh
      - name: Prepare release for ocg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: Chinwendu20/otel_components_generator
          CANDIDATE_BETA: ${{ inputs.candidate-beta }}
          CANDIDATE_STABLE: ${{ inputs.candidate-stable }}
          CURRENT_BETA: ${{ inputs.current-beta }}
          CURRENT_STABLE: ${{ inputs.current-stable }}
        run: ./.github/workflows/scripts/release-prepare-release.sh
